import type { Metadata } from "next";
import "../globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Nav from "@/components/nav/nav.component";
import { Cairo } from "next/font/google";
import About from "@/components/footer/index.component";
import React from "react";
import { Provider } from "./provider";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  console.log(locale);
  if (!routing.locales.includes(locale as Locales)) {
    notFound();
  }

  const messages = await getMessages();
  const direction = locale === "ar" ? "rtl" : "ltr";

  const className = cairo.className;

  // Ensure children is serializable (plain object or React nodes)
  const isValidChildren = React.isValidElement(children) ? children : null;

  return (
    <html lang={locale} dir={direction}>
      <body className={className + " antialiased"} dir={direction}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Provider>
            <div className={`flex flex-col min-h-screen `}>
              <Nav lang={locale} dir={direction} />
              <div className="flex-grow overflow-auto">
                {isValidChildren}
              </div>{" "}
              <About />
            </div>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
