import type { Metadata } from "next";
import "../globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Nav from "@/components/nav/nav.component";
import { Cairo } from "next/font/google";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as "ar" | "en")) {
    notFound();
  }

  const messages = await getMessages();
  const direction = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={direction}>
      <body className={cairo.className + " antialiased"} dir={direction}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className={`flex flex-col h-screen `}>
            <Nav lang={locale} dir={direction} />
            <div className="flex-grow overflow-auto">{children}</div>{" "}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
